### PR TITLE
Sprint20 update poisson

### LINKED ISSUE #17: Case: Poisson
Waiting on 
- [x] https://github.com/CUQI-DTU/CUQIpy/issues/209
- [x] https://github.com/CUQI-DTU/CUQIpy/issues/211
- [x] https://github.com/CUQI-DTU/CUQIpy/issues/207
- [x] https://github.com/CUQI-DTU/CUQIpy-FEniCS/issues/57

### PR DESCRIPTION
**Pull request by amal-ghamdi**
closes #17

### CODE REVIEW

**Comment by amal-ghamdi** [comment]
Hi @jakobsj, @nabriis, would it be possible that either of you review this PR. I think this demo is finalized now to go with the paper. Many thanks!

**Comment by amal-ghamdi** [comment]
Thank you @jakobsj for taking a look!

this issue back to "in progress" now to remove warnings

**Review by jakobsj — APPROVED** [review]
Hi @amal-ghamdi, it looks good now thanks!  My only tiny suggestion, which does not require re-review, would be to either remove the section titles at the top, which do not appear fully up to date, or to add a few more section titles at appropriate places throughout the notebook as e.g. done in the heat case.

**Comment by amal-ghamdi** [comment]
Thank you @jakobsj for your review! 

Yes I think the title could be improved. I made it this way to match the paper titles (1. Introduction) and (1.2. A motivating example). 

Now I updated it to be: (Code for CUQIpy paper 2, section 1.2. A motivating example), similar to what is used in part 1 titles.

**Pull request merged**
